---
output: github_document
---

# Mini reporte (dslab)

Utiliza la API de twitter para menciones de cuentas de politica en Chile.
Fecha del reporte: `r Sys.time()`

```{r actualizar twitter, warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
invisible({
  source("politics/mencion_cuentas.R", echo = FALSE)
})
```

# Hashtags más populares

```{r hashtags, warning=FALSE}
# Leer achivos
datos <- lapply(archivos_creados, data.table::fread)
datos <- lapply(datos, "[[", "text")
datos <- unlist(datos)

# Extrayendo info
datos <- stringr::str_extract_all(datos, "#[[:alnum:]_]+")
datos <- unlist(datos)

datos <- table(datos)
datos <- as.data.frame(datos, responseName = "Cuenta")

datos <- datos[order(datos$Cuenta, decreasing = TRUE),,drop=FALSE]
knitr::kable(head(datos, 20), row.names = FALSE)
```

# Cuentas

```{r lista-cuentas, echo=FALSE}
cuentas <- read.csv("politics/cuentas-politicas.csv", stringsAsFactors = FALSE)
cuentas$cuenta <- sprintf("<a href=\"https://twitter.com/%s\" target=\"_blank\">@%s</a>", cuentas$cuenta, cuentas$cuenta)
knitr::kable(cuentas, escape = FALSE)
```

