name: Build report

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1-5' # Lunes a Viernes a las 00 horas.

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages(c("renv", "data.table", "httr", "rmarkdown"))'
          R -e 'renv::restore()'
          R -e 'cat("This is my secret: ", Sys.getenv("MY_SECRET"),"\n")'
      - name: Render Rmarkdown files
        run: |
          RMD_PATH=minireporte.Rmd #($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m 'Re-build Rmarkdown files'
          git push origin || echo "No changes to commit"
